// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Generated Protobuf types from `onnx.proto`.
//!
//! These types are generated by `prost-build` at compile time from the
//! vendored `proto/onnx.proto` schema.

pub mod onnx {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}
